### ISSUE TITLE
게임 QA 자문 요청을 위한 인물탐색

### ISSUE THREAD

**Issue by akillness** [eglabsid/EGLab#2]
총 3명 문의 진행중

1. 넷게임즈 FunQA 1명
2. NC QA 1명 -1
4. 넥슨 QA출신 기획자 자문 대기

**Comment by akillness** [comment]
인건비 지급관련 보류 상황으로 인해, Backlog

**Comment by eglabsid** [comment]
추후 진행될 여지가 없어보이므로 완료처리함
