### ISSUE TITLE
QA 자문을 위한 질문 내역 작성

### ISSUE THREAD

**Issue by akillness** [eglabsid/EGLab#3]
우선, QA업무에 대한 전반적인 이해를 바탕으로 하기 위한 도서 참고

QA 업무 : ex) TQA, FunQA 등

1. 평가하려는 지표 (요소) 
2. 지표를 선정한 이유가 있을지?
3. 평가된 지표를 프로그래머, 기획자, 아트에게 전달하는 일종의 전반적인 워크플로우가 어떻게 되는지?
4. 버그, 티켓 등 수정 요소에 대해 피드백을 전달하는 방식?
5. 업무 루틴이 있다면 어떤 것일까?
6. ..

등등

구글시트로 작성하여, 자문료 지급시 필요한 내용 숙지 후 취합하기  

--- 

게임 QA 요소

- 요구문서
- 필요한 정보(요소)
- 프로젝트 요구사항
- planning poker로 추정치 : 개인 역량차이 평준화, 불확실한 추정치
- 추정치 기준 값은 작업범위에 한정

게임 QA의 추정치 변화 요인
- 경험 많은 QA의 조언
- 지난 프로젝트의 경험
- 팀 변경이나 요구사항 변경

추정치의 의미(Estimation)
- 일반적으로는 작업일 산정을 위해 일 단위로 추정치로 사용하지만, 프로젝트 요구사항마다의 영향력을 추정치로 표현할 수 있지 않을까?

추정치 산정 방법(Method)
- 비교기반추정 : 유사한 프로젝트인지 판단? 맞다면, 과거데이터를 Baseline으로 활용
**- > 프로젝트의 요구사항 내역의 유사성 수치 이용**
- 작업분할방식 : 프로젝트의 기획적, 기능적 요구사항을 더 작은 작업으로 나누기
- >최소 단위의 작업으로 쪼개어 전체 작업량 산정
**- >> 작은 작업으로 나누는데 LLM 적용도 가능할듯?**
- Planning Poker : consensus-based technique(합의기반기술)

**Comment by eglabsid** [comment]
구글폼 작성 및 가은님에게 전달[완료] @ldr77a 

링크 : https://docs.google.com/forms/d/1XPocBxxm3LNlByAtQPGZcv6ZzaEfJjFQA-v2vGrtvmo/edit
