### ISSUE TITLE
AutoQA 툴 제작

### ISSUE THREAD

**Issue by RedDice333** [eglabsid/EGLab#4]
현재 진행중인 파이썬 기반 AutoQA 툴 제작.
해야 할 목록.
1. UI 초기 제작 (완료)
2. 버튼 동작 구현 (진행중)
3. 자동 전투 시스템 구현(진행중)

**Comment by akillness** [comment]
해당 구현은 일감 이관으로 아래의 일감으로 변경하여 완료처리함
- https://github.com/users/eglabsid/projects/2/views/1?pane=issue&itemId=81246591
