### ISSUE TITLE
QA 지표 세우기

### ISSUE THREAD

**Issue by ldr77a** [eglabsid/EGLab#6]

**Comment by ldr77a** [comment]
R. Ramadan and B. Hendradjaya, “Development of game testing method for measuring game quality”, International Conference on Data and Software Engineering (ICODSE), 2014

**Comment by ldr77a** [comment]
~9월 13일 (금요일)
게임 장르 2개 선택 후 각각 QA 지표 설립.

**Comment by ldr77a** [comment]
~9월 18일 (수요일) 게임 장르 총 6개, QA 지표 설립

- MMORPG
- 퍼즐 게임
- 슈팅 게임
- 리듬 게임
- 경영 시뮬레이션
- 디펜스

**Comment by ldr77a** [comment]
QA 지표 정량적으로 수정
Feature Availability, Balance(result) 위주로.

- MMORPG: 임의로 게임 디자인 진행
- 퍼즐 게임: S.Voinov, Level Design Case Studies: Trainyard and Cut the Rope. Game Developers Conference 2012
https://gamedevforever.com/146

**Comment by eglabsid** [comment]
그래프 지표 작성 및 2024년 성과평과용 보고서 작성이 마무리되어 완료처리함
